import "@/styles/globals.css"

import type { Metadata } from "next"
import { irsans } from "@/assets/fonts"
import NextTopLoader from "nextjs-toploader"

import { SaveCarts } from "@/components/SaveCarts"
import { SiteLayout } from "@/components/site/SiteLayout"
import ReduxProvider from "@/components/ReduxProvider"

export const metadata: Metadata = {
  title: "Next Cart App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={irsans.className}>
        <NextTopLoader
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
        />
        <ReduxProvider>
          <SiteLayout>{children}</SiteLayout>
          <SaveCarts /> 
        </ReduxProvider>
      </body>
    </html>
  )
}
