import "@/styles/globals.css"

import type { Metadata } from "next"
import { irsans } from "@/assets/fonts"

import { SaveCarts } from "@/components/SaveCarts"
import { SiteLayout } from "@/components/site/SiteLayout"

export const metadata: Metadata = {
  title: "Next Cart App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={irsans.className}>
        <SiteLayout>{children}</SiteLayout>
        <SaveCarts />
      </body>
    </html>
  )
}
